apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-orpy
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-wnpp-tenant/rhtap-demo-app/hacbs-test-project-orpy@sha256:a8aea7a69af2bde9e64269fb6acf27292dfbb7f78d69414ae7d9c1625ee18ac3
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
